### ISSUE TITLE
Issue with HACS Integration for "nier-theme" 

### ISSUE THREAD

**Issue by Akhenath** [exloseur3d/nier-theme#14]
Hello,

I just wanted to reach out to congratulate you on the amazing theme you created for Home Assistant! I've been looking for something exactly like this, and I absolutely love it.

However, I wasn't able to integrate it via HACS because the repository seems to be non-compliant. I received the following error message:
<Theme exloseur3d/nier-theme> Repository structure for v0.1.11 is not compliant.

I look forward to being able to use this theme soon and enjoy all its features. Thank you in advance!

Best regards,

**Comment by exloseur3d** [comment]
This theme is for Obsidian i am not sure of what is hacs?

**Comment by Akhenath** [comment]
Hi,

Indeed, I came across this template while browsing forums on Home Assistant themes. Since it was exactly the style I was looking for, I didn’t notice that it was actually for Obsidian and not Home Assistant.

Sorry for the confusion. In any case, congratulations once again, as it’s incredibly true to the original work.

Thanks!

**Comment by exloseur3d** [comment]
Thank you, i hope you can find a similar theme for your need !
